In [1]:
import numpy as np    #INSERT (1D)
arr=np.array([10,20,30,40,50])
new_arr=np.insert(arr,2,100)
print(new_arr)

[ 10  20 100  30  40  50]


In [8]:
import numpy as np     #INSERT(2D)
arr_2d=np.array([[1,2,3],[4,5,6]])
new_arr_2d=np.insert(arr_2d,0,[5,6],1)
print(new_arr_2d)

[[5 1 2 3]
 [6 4 5 6]]


In [12]:
import numpy as np   #Append
arr=np.array([[10,20,30]])
new_ar=np.append(arr,[[40,50,60]])
print(new_ar)

[10 20 30 40 50 60]


In [13]:
import numpy as np   #Concatenate
arr1=np.array([[10,20,30]])
arr2=np.array([[40,50,60]])

new_ar=np.concatenate((arr1,arr2))
print(new_ar)



[[10 20 30]
 [40 50 60]]


In [14]:
import numpy as np  #REMOVING (1D)

arr_1=np.array([1,2,3,4,5,6])
new_arr=np.delete(arr_1,0)
print(new_arr)

[2 3 4 5 6]


In [16]:
import numpy as np   #REMOVING (2D)
arr_2=np.array([[1,2,3],[4,5,6]])
new_arr_2d=np.delete(arr_2d,0,axis=0)
print(new_arr_2d)

[[4 5 6]]


In [18]:
import numpy as np      #STACKING
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [20]:
import numpy as np      #SPLITTING

arr=np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]
