In [1]:
!pip install Numpy


In [3]:
import numpy as np
marks=np.array([10,20,30,40])
print(marks)

[10 20 30 40]


In [5]:
import numpy as np
marks=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(marks)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
zeros_array = np.zeros(3)  
print(zeros_array)

[0. 0. 0.]


In [10]:
import numpy as np
ones_array=np.ones(3)
print(ones_array)

[1. 1. 1.]


In [14]:
import numpy as np
numbers_array=np.full( (3,3) , ( 5))
print(numbers_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [21]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
