In [1]:
import numpy as np    #Broadcasting  
prices=np.array([100,200,300,400,500])
discount=10

final_prices=prices-(prices*discount/100)
print(final_prices)


[ 90. 180. 270. 360. 450.]


In [4]:
import numpy as np   #single value

arr=np.array([1,2,3,4,5,6])
result=arr*2
print(result)


[ 2  4  6  8 10 12]


In [6]:
import numpy as np  #1d and 2d array addition

matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])

result=matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [7]:
import numpy as np   #Vectorization

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

result=arr1+arr2
print(result)

[5 7 9]
