In [2]:
import numpy as np  #isnan used to detect missing values
arr=np.array([1,2,np.nan,4,5,np.nan])
print(np.isnan(arr))

[False False  True False False  True]


In [3]:
import numpy as np    #np.nan_to_num used to replace the values of nan

arr=np.array([1,2,np.nan,4,5,np.nan])
cleaned_arr=np.nan_to_num(arr,nan=10)
print(cleaned_arr)


[ 1.  2. 10.  4.  5. 10.]


In [4]:
import numpy as np    #np.nan_to_num used to replace the values of nan

arr=np.array([1,2,np.nan,4,5,np.nan])
cleaned_arr=np.nan_to_num(arr)
print(cleaned_arr)

[1. 2. 0. 4. 5. 0.]


In [5]:
import numpy as np  #np.isinf detects if infinite value is present

arr=np.array([1,2,np.inf,4,5,-np.inf])

print(np.isinf(arr))


[False False  True False False  True]


In [6]:
import numpy as np  # posinf changes value in at place of positive infinite number same as neginf at negative infinte number

arr=np.array([1,2,np.inf,4,5,-np.inf])

print(np.isinf(arr))

cleaned_arr=np.nan_to_num(arr,posinf=100,neginf=100)
print(cleaned_arr)

[False False  True False False  True]
[  1.   2. 100.   4.   5. 100.]
