In [2]:
import numpy as np   #SLICING
arr=np.array([10,20,30,40,50])

print(arr[1])
print(arr[3])
print(arr[0])
print(arr[-1])

20
40
10
50


In [5]:
import numpy as np #SLICING
arr=np.array([10,20,30,40,50,60])

print(arr[1:3])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[20 30]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [8]:
import numpy as np  #Fancy Indexing
 
arr=np.array([10,20,30,40,50,60])

print(arr[[0,2,4]])


[10 30 50]


In [9]:
import numpy as np   #Boolean Masking
arr=np.array([10,20,30,40,50,60])

print(arr[arr>25])



[30 40 50 60]
