In [3]:
import numpy as np    #Mathematical operations
arr=np.array([1,2,3,4,5,6])

print(arr+5)
print(arr-2)
print(arr*2)


[ 6  7  8  9 10 11]
[-1  0  1  2  3  4]
[ 2  4  6  8 10 12]


In [4]:
import numpy as np       # Aggregation Function
arr=np.array([10,20,30,40,50,60])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))

210
35.0
17.07825127659933
10
60
291.6666666666667
