In [1]:
import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr = np.ones((3, 3), dtype=bool)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
arr = np.arange(10)
even = arr[arr % 2 == 0]
print(even)


[0 2 4 6 8]


In [4]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [5]:
arr = np.arange(9)
reshaped = arr.reshape(3, 3)
print(reshaped)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked = np.vstack((a, b))
print(stacked)


[[1 2 3]
 [4 5 6]]


In [7]:
identity = np.eye(4)
print(identity)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
rand_arr = np.random.rand(2, 3)
print(rand_arr)


[[0.18407004 0.80605166 0.66732868]
 [0.56524024 0.56763301 0.60872811]]


In [9]:
arr = np.array([4, 10, 2, 8])
print("Max:", np.max(arr))
print("Min:", np.min(arr))


Max: 10
Min: 2


In [10]:
arr = np.array([0, 3, 0, 7, 0, 9])
indices = np.nonzero(arr)
print(indices)


(array([1, 3, 5]),)
