In [1]:
import numpy as np

# Create a 3x3 array of zeros
a = np.zeros((3, 3))
print("Zeros:\n", a)

# Create a 4x4 identity matrix
i = np.eye(4)
print("Identity:\n", i)

# Create a random array of shape (2, 5)
r = np.random.rand(2, 5)
print("Random:\n", r)

# Create an array with a range of values
arr = np.arange(10, 30, 5)
print("Range:\n", arr)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random:
 [[0.94756876 0.43380996 0.27318013 0.95537271 0.29603939]
 [0.46638705 0.76766382 0.91816415 0.48779146 0.3614553 ]]
Range:
 [10 15 20 25]


In [2]:
a = np.array([[10, 20, 30], [40, 50, 60]])

# Access element at first row, second column
print(a[0, 1])  # Output: 20

# Slice the second column
print(a[:, 1])  # Output: [20 50]

# Boolean indexing
print(a[a > 30])  # Output: [40 50 60]


20
[20 50]
[40 50 60]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array
print(a.flatten())

# Reshape to 3x2
print(a.reshape(3, 2))

# Concatenate arrays
b = np.array([[7, 8, 9]])
print(np.concatenate((a, b), axis=0))

# Split array into two parts
print(np.split(a, 2))


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [4]:
a = np.array([[1, 2], [3, 4]])

# Element-wise operations
print(a + 10)
print(a * 2)

# Aggregation
print("Sum:", np.sum(a))
print("Mean (axis=0):", np.mean(a, axis=0))   #Column wise mean
print("Std deviation:", np.std(a))


[[11 12]
 [13 14]]
[[2 4]
 [6 8]]
Sum: 10
Mean (axis=0): [2. 3.]
Std deviation: 1.118033988749895


In [7]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Broadcasting: a (3x1) + b (1x3) = (3x3)
print(a + b)

# Vectorized squaring
x = np.array([1, 2, 3, 4])
print(x ** 2)

print("Vectorized:", x ** 2)


[11 22 33]
[ 1  4  9 16]
Vectorized: [ 1  4  9 16]
