In [1]:
import numpy as np # RESHAPING
arr=np.array([10,20,30,40,50,60])
reshaped_arr=arr.reshape(2,3)      #2 ROWS 3 COLUMNS
print(reshaped_arr)

[[10 20 30]
 [40 50 60]]


In [10]:
import numpy as np      #Flatten it does not affects the original array
arr_2d=np.array([[1,2],[4,5]])
flat=arr_2d.flatten()
flat[0]=100
print(arr_2d)
print(flat)

[[1 2]
 [4 5]]
[100   2   4   5]


In [12]:
import numpy as np     #Ravel it actually affects the original array
arr_2d=np.array([[1,2],[4,5]])
ravel=arr_2d.ravel()
ravel[0]=100
print(arr_2d)
print(ravel)

[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]
[100   2   4   5]
